apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 383140420017.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:702b1cc19bfe3bf1c120be5cef7642c6cca156f5
        ports:
        - containerPort: 80
