apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 383140420017.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:ebb48c7725e63b7dd66d34a384cae51717a91dcb
        ports:
        - containerPort: 80
